# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCMADPU01():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cMADPU01(self):
    # Ir a la página de login
    self.driver.get("http://localhost:5173/login")
    
    # Llenar formulario de login
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("fabricio15alex@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("14052003@leX")
    
    # Hacer clic en el botón de login
    self.driver.find_element(By.CSS_SELECTOR, ".whitespace-nowrap").click()
    
    # Esperar a estar en dashboard
    WebDriverWait(self.driver, 10).until(
        expected_conditions.url_contains("/dashboard")
    )
    
    # Verificar que estamos en el dashboard
    assert "/dashboard" in self.driver.current_url
    
    # Verificar que las tarjetas de estadísticas están visibles y muestran datos
    
    # Tarjeta 1: Usuarios Activos
    usuarios_card = WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(text(), 'Usuarios Activos')]"))
    )
    assert usuarios_card.is_displayed()
    
    # Verificar que muestra un número (no está en carga "…")
    usuarios_value = self.driver.find_element(By.XPATH, "//div[contains(text(), 'Usuarios Activos')]/../..//div[contains(@class, 'text-3xl')]")
    assert usuarios_value.text != "…" and usuarios_value.text != ""
    
    # Tarjeta 2: Incidencias  
    incidencias_card = self.driver.find_element(By.XPATH, "//div[contains(text(), 'Incidencias')]")
    assert incidencias_card.is_displayed()
    
    incidencias_value = self.driver.find_element(By.XPATH, "//div[contains(text(), 'Incidencias')]/../..//div[contains(@class, 'text-3xl')]")
    assert incidencias_value.text != "…" and incidencias_value.text != ""
    
    # Tarjeta 3: Reportes
    reportes_card = self.driver.find_element(By.XPATH, "//div[contains(text(), 'Reportes')]")
    assert reportes_card.is_displayed()
    
    reportes_value = self.driver.find_element(By.XPATH, "//div[contains(text(), 'Reportes')]/../..//div[contains(@class, 'text-3xl')]")
    assert reportes_value.text != "…" and reportes_value.text != ""
    
    # Tarjeta 4: Productos
    productos_card = self.driver.find_element(By.XPATH, "//div[contains(text(), 'Productos')]")
    assert productos_card.is_displayed()
    
    productos_value = self.driver.find_element(By.XPATH, "//div[contains(text(), 'Productos')]/../..//div[contains(@class, 'text-3xl')]")
    assert productos_value.text != "…" and productos_value.text != ""
    
    print("✅ CM-ADPU01: Todas las tarjetas de estadísticas verificadas correctamente")