# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCMADAU03():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cMADAU03(self):
    # Ir a la página de login
    self.driver.get("http://localhost:5173/login")
    
    # Llenar formulario de login
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("fabricio15alex@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("14052003@leX")
    
    # Hacer clic en el botón de login
    self.driver.find_element(By.CSS_SELECTOR, ".whitespace-nowrap").click()
    
    # Esperar a que el login se complete y se redirija al dashboard
    # Esperamos que aparezca algún elemento específico del dashboard
    try:
        WebDriverWait(self.driver, 15).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestionar Usuarios"))
        )
    except:
        # Si no encuentra "Gestionar Usuarios", puede que necesite ir al dashboard manualmente
        self.driver.get("http://localhost:5173/dashboard")
        WebDriverWait(self.driver, 10).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestionar Usuarios"))
        )
    
    # Hacer clic en "Gestionar Usuarios"
    gestionar_usuarios_link = self.driver.find_element(By.LINK_TEXT, "Gestionar Usuarios")
    gestionar_usuarios_link.click()
    
    # Esperar a que se cargue la página de gestión de usuarios
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.XPATH, "//h1[contains(text(), 'Gestión de Usuarios')]"))
    )
    
    print("✅ Página de gestión de usuarios cargada correctamente")
    
    # Esperar a que se cargue la tabla de usuarios
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "table"))
    )
    
    # Buscar un usuario suspendido para reactivar
    # Excluir el usuario admin actual y buscar usuarios con estado "Suspendido"
    user_rows = self.driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    
    if len(user_rows) == 0:
      pytest.fail("No se encontraron usuarios en la tabla")
    
    target_user = None
    target_row = None
    
    for row in user_rows:
      try:
        # Obtener el email del usuario de esta fila
        email_element = row.find_element(By.CSS_SELECTOR, "div.flex.items-center.text-sm.text-gray-600")
        user_email = email_element.text.strip()
        
        # Verificar que no sea el usuario admin actual
        if user_email == "fabricio15alex@gmail.com":
          continue
        
        # Verificar que el usuario esté suspendido
        status_badge = row.find_element(By.XPATH, ".//span[contains(@class, 'bg-green-100') or contains(@class, 'bg-red-100')]")
        status_text = status_badge.text.strip()
        
        if status_text == "Suspendido":
          # Verificar que tenga un menú de acciones (botón con los tres puntos)
          action_buttons = row.find_elements(By.XPATH, ".//button[.//*[local-name()='svg']]")
          if len(action_buttons) > 0:
            target_user = user_email
            target_row = row
            print(f"✅ Usuario suspendido encontrado: {target_user}")
            break
            
      except Exception as e:
        print(f"⚠️ Error al procesar fila de usuario: {str(e)}")
        continue
    
    if not target_user or not target_row:
      pytest.fail("No se encontró ningún usuario suspendido disponible para reactivar. Ejecute primero CM-ADAU01 o CM-ADAU02 para suspender un usuario.")
    
    # Hacer clic en el botón de acciones (los tres puntos)
    # Como ya validamos que target_row no es None, podemos proceder
    assert target_row is not None, "target_row no puede ser None en este punto"
    action_button = target_row.find_element(By.XPATH, ".//button[.//*[local-name()='svg']]")
    # Asegurar visibilidad y evitar intercepts al hacer clic
    self.driver.execute_script("arguments[0].scrollIntoView({block:'center'});", action_button)
    try:
      action_button.click()
    except Exception:
      # Fallback: intento con JS click y luego con Actions
      self.driver.execute_script("arguments[0].click();", action_button)
      ActionChains(self.driver).move_to_element(target_row).move_to_element(action_button).pause(0.1).click().perform()
    
    print("✅ Menú de acciones desplegado")
    
    # Esperar a que aparezca el dropdown menu y hacer clic en "Reactivar"
    menu_locator = (By.XPATH, "//div[contains(text(), 'Reactivar')]")
    WebDriverWait(self.driver, 8).until(expected_conditions.visibility_of_element_located(menu_locator))
    reactivate_option = self.driver.find_element(*menu_locator)
    self.driver.execute_script("arguments[0].scrollIntoView({block:'center'});", reactivate_option)
    try:
      reactivate_option.click()
    except Exception:
      self.driver.execute_script("arguments[0].click();", reactivate_option)
    
    print("✅ Opción 'Reactivar' seleccionada")
    
    # La reactivación es directa, no requiere modal de confirmación
    # Solo esperamos a que se actualice la lista
    time.sleep(3)
    
    # Buscar de nuevo el usuario en la tabla para verificar que fue reactivado
    updated_user_rows = self.driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    user_reactivated = False
    
    for row in updated_user_rows:
      try:
        # Obtener el email del usuario de esta fila
        email_element = row.find_element(By.CSS_SELECTOR, "div.flex.items-center.text-sm.text-gray-600")
        user_email = email_element.text.strip()
        
        if user_email == target_user:
          # Verificar el estado del usuario
          status_badge = row.find_element(By.XPATH, ".//span[contains(@class, 'bg-green-100') or contains(@class, 'bg-red-100')]")
          status_text = status_badge.text.strip()
          
          if status_text == "Activo":
            user_reactivated = True
            print(f"✅ Usuario {target_user} fue reactivado exitosamente")
            break
          else:
            print(f"❌ Usuario {target_user} sigue con estado: {status_text}")
            
      except Exception as e:
        print(f"⚠️ Error al verificar estado del usuario: {str(e)}")
        continue
    
    if not user_reactivated:
      pytest.fail(f"El usuario {target_user} no fue reactivado correctamente")
    
    print("✅ Test completado: Usuario reactivado de forma exitosa")
  