# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.alert import Alert

class TestCMADCU01():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cMADCU01(self):
    # Ir a la página de login
    self.driver.get("http://localhost:5173/login")
    
    # Llenar formulario de login
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("fabricio15alex@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("14052003@leX")
    
    # Hacer clic en el botón de login
    self.driver.find_element(By.CSS_SELECTOR, ".whitespace-nowrap").click()
    
    # Esperar a que el login se complete y se redirija al dashboard
    # Esperamos que aparezca algún elemento específico del dashboard
    try:
        WebDriverWait(self.driver, 15).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestionar Usuarios"))
        )
    except:
        # Si no encuentra "Gestionar Usuarios", puede que necesite ir al dashboard manualmente
        self.driver.get("http://localhost:5173/dashboard")
        WebDriverWait(self.driver, 10).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestionar Usuarios"))
        )
    
    # Hacer clic en "Gestionar Usuarios"
    gestionar_usuarios_link = self.driver.find_element(By.LINK_TEXT, "Gestionar Usuarios")
    gestionar_usuarios_link.click()
    
    # Esperar a que se cargue la página de gestión de usuarios
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.XPATH, "//h1[contains(text(), 'Gestión de Usuarios')]"))
    )
    
    # Buscar en la tabla un usuario que:
    # 1. NO tenga el correo admin@sistema.com
    # 2. Tenga botón de acciones disponible (que sea eliminable)
    # Primero esperamos a que la tabla se cargue
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "table tbody tr"))
    )
    
    # Contar usuarios antes de la eliminación
    initial_user_rows = self.driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    initial_user_count = len(initial_user_rows)
    print(f"Número de usuarios antes de la eliminación: {initial_user_count}")
    
    target_user_row = None
    target_user_name = None
    target_user_email = None
    
    for row in initial_user_rows:
      # Obtener el email del usuario para verificar que no sea admin@sistema.com
      email_element = row.find_element(By.CSS_SELECTOR, "div.flex.items-center.text-sm.text-gray-600")
      user_email = email_element.text
      
      # Verificar que NO sea el admin central
      if user_email != "fabricio15alex@gmail.com":
        # Verificar que tenga botón de acciones (que sea gestionable)
        action_buttons = row.find_elements(By.CSS_SELECTOR, "button[aria-haspopup='menu']")
        if len(action_buttons) > 0:
          target_user_row = row
          # Obtener información del usuario antes de eliminarlo
          user_name_element = target_user_row.find_element(By.CSS_SELECTOR, "p.font-medium")
          target_user_name = user_name_element.text
          target_user_email = user_email
          break
    
    # Si encontramos un usuario válido, proceder con la eliminación
    if target_user_row is not None:
      print(f"Eliminando usuario: {target_user_name} (email: {target_user_email})")
      
      # Hacer clic en el botón de acciones (MoreHorizontal)
      action_button = target_user_row.find_element(By.CSS_SELECTOR, "button[aria-haspopup='menu']")
      action_button.click()
      
      # Esperar a que aparezca el menú desplegable y buscar "Eliminar"
      WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(text(), 'Eliminar')]"))
      )
      
      # Hacer clic en "Eliminar" (elemento con texto rojo)
      delete_option = self.driver.find_element(By.XPATH, "//div[contains(text(), 'Eliminar')]")
      delete_option.click()
      
      # Esperar y manejar la alerta de confirmación de JavaScript
      WebDriverWait(self.driver, 5).until(expected_conditions.alert_is_present())
      alert = Alert(self.driver)
      
      # Verificar que el mensaje de confirmación sea el correcto
      alert_text = alert.text
      expected_message = "¿Estás seguro de que quieres eliminar este usuario? Esta acción no se puede deshacer."
      assert expected_message in alert_text, f"El mensaje de confirmación no coincide. Esperado: '{expected_message}', Actual: '{alert_text}'"
      
      # Confirmar la eliminación
      alert.accept()
      
      # Esperar a que aparezca el mensaje de éxito (toast)
      WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(text(), 'Usuario eliminado')]"))
      )
      
      # Verificar que el usuario fue eliminado correctamente
      # Esperar a que se recargue la tabla
      time.sleep(3)  # Dar tiempo a que se recargue la tabla
      
      # Verificar que la tabla se actualice (después del refresh)
      WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "table tbody tr"))
      )
      
      # Contar usuarios después de la eliminación
      final_user_rows = self.driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
      final_user_count = len(final_user_rows)
      print(f"Número de usuarios después de la eliminación: {final_user_count}")
      
      # Verificar que el número de usuarios se redujo en 1
      assert final_user_count == initial_user_count - 1, f"El número de usuarios debería haberse reducido en 1. Inicial: {initial_user_count}, Final: {final_user_count}"
      
      # Verificar que el usuario específico ya no esté en la lista
      user_still_exists = False
      for row in final_user_rows:
        name_elements = row.find_elements(By.CSS_SELECTOR, "p.font-medium")
        if len(name_elements) > 0 and name_elements[0].text == target_user_name:
          user_still_exists = True
          break
      
      assert not user_still_exists, f"El usuario '{target_user_name}' aún aparece en la tabla después de ser eliminado"
      
      print(f"✅ Usuario '{target_user_name}' eliminado correctamente")
      
    else:
      pytest.skip("No se encontró ningún usuario válido (que no sea admin@sistema.com) para eliminar en el test")
  