# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCMADGU01():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cMADGU01(self):
    # Ir a la página de login
    self.driver.get("http://localhost:5173/login")
    
    # Llenar formulario de login
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("fabricio15alex@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("14052003@leX")
    
    # Hacer clic en el botón de login
    self.driver.find_element(By.CSS_SELECTOR, ".whitespace-nowrap").click()
    
    # Esperar a que el login se complete y se redirija al dashboard
    # Esperamos que aparezca algún elemento específico del dashboard
    try:
        WebDriverWait(self.driver, 15).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestionar Usuarios"))
        )
    except:
        # Si no encuentra "Gestionar Usuarios", puede que necesite ir al dashboard manualmente
        self.driver.get("http://localhost:5173/dashboard")
        WebDriverWait(self.driver, 10).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestionar Usuarios"))
        )
    
    # Hacer clic en "Gestionar Usuarios"
    gestionar_usuarios_link = self.driver.find_element(By.LINK_TEXT, "Gestionar Usuarios")
    gestionar_usuarios_link.click()
    
    # Esperar a que se cargue la página de gestión de usuarios
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.XPATH, "//h1[contains(text(), 'Gestión de Usuarios')]"))
    )
    
    # Buscar en la tabla un usuario que NO tenga rol de Moderador
    # Primero esperamos a que la tabla se cargue
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "table tbody tr"))
    )
    
    # Buscar todas las filas de usuarios en la tabla
    user_rows = self.driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    
    target_user_row = None
    for row in user_rows:
      # Buscar el badge del rol en cada fila
      role_badges = row.find_elements(By.CSS_SELECTOR, ".bg-blue-100.text-blue-800")
      # Si no encuentra el badge azul (que es el de moderador), entonces es un usuario sin rol de moderador
      if len(role_badges) == 0:
        # Verificar que tenga botón de acciones (que sea gestionable)
        action_buttons = row.find_elements(By.CSS_SELECTOR, "button[aria-haspopup='menu']")
        if len(action_buttons) > 0:
          target_user_row = row
          break
    
    # Si encontramos un usuario válido, proceder con el cambio de rol
    if target_user_row is not None:
      # Obtener información del usuario antes de hacer el cambio (para verificar después)
      user_name_element = target_user_row.find_element(By.CSS_SELECTOR, "p.font-medium")
      user_name = user_name_element.text
      print(f"Cambiando rol del usuario: {user_name}")
      
      # Hacer clic en el botón de acciones (MoreHorizontal) con manejo anti-intercepts
      action_button = target_user_row.find_element(By.CSS_SELECTOR, "button[aria-haspopup='menu']")
      self.driver.execute_script("arguments[0].scrollIntoView({block:'center'});", action_button)
      try:
        action_button.click()
      except Exception:
        self.driver.execute_script("arguments[0].click();", action_button)
        ActionChains(self.driver).move_to_element(target_user_row).move_to_element(action_button).pause(0.1).click().perform()
      
      # Esperar a que aparezca el menú desplegable con opciones visibles
      change_role_locator = (By.XPATH, "//div[contains(text(), 'Cambiar Rol')]")
      WebDriverWait(self.driver, 10).until(
        expected_conditions.visibility_of_element_located(change_role_locator)
      )
      # Hacer clic en "Cambiar Rol" con espera y fallback
      change_role_option = self.driver.find_element(*change_role_locator)
      self.driver.execute_script("arguments[0].scrollIntoView({block:'center'});", change_role_option)
      try:
        change_role_option.click()
      except Exception:
        self.driver.execute_script("arguments[0].click();", change_role_option)
      
      # Esperar a que aparezca el submenú de roles (visible)
      moderator_locator = (By.XPATH, "//div[contains(text(), 'Moderador')]")
      WebDriverWait(self.driver, 10).until(
        expected_conditions.visibility_of_element_located(moderator_locator)
      )
      
      # Hacer clic en "Moderador" con espera y fallback
      moderator_option = self.driver.find_element(*moderator_locator)
      self.driver.execute_script("arguments[0].scrollIntoView({block:'center'});", moderator_option)
      try:
        moderator_option.click()
      except Exception:
        self.driver.execute_script("arguments[0].click();", moderator_option)
      
      # Esperar a que aparezca el mensaje de éxito (toast)
      WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.XPATH, "//div[contains(text(), 'Rol actualizado correctamente')]"))
      )
      
      # Verificar que el rol se cambió correctamente
      # Esperar a que se recargue la tabla y buscar nuevamente al usuario
      time.sleep(3)  # Dar tiempo a que se recargue la tabla
      
      # Buscar nuevamente todas las filas de la tabla (después del refresh)
      WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "table tbody tr"))
      )
      
      # Buscar la fila del usuario que acabamos de modificar por su nombre
      updated_user_rows = self.driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
      user_found_with_moderator_role = False
      
      for row in updated_user_rows:
        # Buscar el nombre del usuario en la fila
        name_elements = row.find_elements(By.CSS_SELECTOR, "p.font-medium")
        if len(name_elements) > 0 and name_elements[0].text == user_name:
          # Verificar que ahora tenga el badge de moderador
          moderator_badges = row.find_elements(By.CSS_SELECTOR, ".bg-blue-100.text-blue-800")
          if len(moderator_badges) > 0:
            user_found_with_moderator_role = True
            print(f"✅ Usuario '{user_name}' ahora tiene rol de Moderador")
            break
      
      assert user_found_with_moderator_role, f"El usuario '{user_name}' debería tener ahora el rol de Moderador"
      
    else:
      pytest.skip("No se encontró ningún usuario sin rol de moderador para realizar el test")
  