# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCMADFA01():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cMADFA01(self):
    # Ir a la página de login
    self.driver.get("http://localhost:5173/login")
    
    # Llenar formulario de login
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("admin@sistema.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    
    # Hacer clic en el botón de login
    self.driver.find_element(By.CSS_SELECTOR, ".whitespace-nowrap").click()
    
    # Esperar a que el login se complete y se redirija al dashboard
    # Esperamos que aparezca algún elemento específico del dashboard
    try:
        WebDriverWait(self.driver, 15).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestionar Usuarios"))
        )
    except:
        # Si no encuentra "Gestionar Usuarios", puede que necesite ir al dashboard manualmente
        self.driver.get("http://localhost:5173/dashboard")
        WebDriverWait(self.driver, 10).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "Gestionar Usuarios"))
        )
    
    # Hacer clic en "Gestionar Usuarios"
    gestionar_usuarios_link = self.driver.find_element(By.LINK_TEXT, "Gestionar Usuarios")
    gestionar_usuarios_link.click()
    
    # Esperar a que se cargue la página de gestión de usuarios
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.XPATH, "//h1[contains(text(), 'Gestión de Usuarios')]"))
    )
    
    # Esperar a que se carguen los filtros
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.XPATH, "//label[contains(text(), 'Mostrar')]"))
    )
    
    print("✅ Página de gestión de usuarios cargada correctamente")
    
    # Localizar el filtro "Mostrar" y hacer clic en él
    # Buscar el select que tiene como label "Mostrar"
    show_filter_label = self.driver.find_element(By.XPATH, "//label[contains(text(), 'Mostrar')]")
    
    # Encontrar el select asociado al label "Mostrar"
    # El select debería estar en el mismo contenedor que el label
    show_filter_container = show_filter_label.find_element(By.XPATH, "./..")
    show_filter_trigger = show_filter_container.find_element(By.CSS_SELECTOR, "button[role='combobox']")
    
    print("✅ Filtro 'Mostrar' localizado")
    
    # Hacer clic en el trigger del select para abrir las opciones
    show_filter_trigger.click()
    
    # Esperar un poco para que se abra el dropdown
    time.sleep(2)
    
    print("✅ Opciones del filtro desplegadas")
    
    # Buscar y hacer clic en "Eliminados"
    # Desde la salida del debug sabemos que funciona con selector de texto general
    eliminados_option = self.driver.find_element(By.XPATH, "//*[contains(text(), 'Eliminados')]")
    eliminados_option.click()
    
    print("✅ Opción 'Eliminados' seleccionada")
    
    # Esperar un momento para que se actualice la selección
    time.sleep(1)
    
    # Hacer clic en el botón "Buscar" para aplicar el filtro
    search_button = self.driver.find_element(By.XPATH, "//button[contains(., 'Buscar')]")
    search_button.click()
    
    print("✅ Filtro aplicado, buscando usuarios eliminados...")
    
    # Esperar a que se cargue la nueva lista filtrada
    # Daremos tiempo para que la tabla se actualice
    time.sleep(3)
    
    # Verificar que la tabla esté presente
    WebDriverWait(self.driver, 10).until(
      expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "table"))
    )
    
    # Buscar las filas de usuarios en la tabla
    try:
      # Intentar encontrar filas de usuarios
      user_rows = self.driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
      
      if len(user_rows) > 0:
        print(f"✅ Se encontraron {len(user_rows)} usuarios eliminados en la lista")
        
        # Verificar que realmente estamos viendo usuarios eliminados
        # Podemos verificar que el filtro esté correctamente aplicado
        # Re-encontrar el elemento del filtro para evitar StaleElementReferenceException
        try:
          show_filter_label_refreshed = self.driver.find_element(By.XPATH, "//label[contains(text(), 'Mostrar')]")
          show_filter_container_refreshed = show_filter_label_refreshed.find_element(By.XPATH, "./..")
          show_filter_trigger_refreshed = show_filter_container_refreshed.find_element(By.CSS_SELECTOR, "button[role='combobox']")
          current_filter_text = show_filter_trigger_refreshed.text
          print(f"Estado actual del filtro: {current_filter_text}")
        except:
          print("⚠️ No se pudo verificar el estado del filtro (puede que haya cambiado la estructura)")
        
        # Mostrar información de algunos usuarios eliminados para verificación
        for i, row in enumerate(user_rows[:3]):  # Mostrar solo los primeros 3
          try:
            user_name_element = row.find_element(By.CSS_SELECTOR, "p.font-medium")
            user_name = user_name_element.text
            
            email_element = row.find_element(By.CSS_SELECTOR, "div.flex.items-center.text-sm.text-gray-600")
            user_email = email_element.text
            
            print(f"Usuario eliminado {i+1}: {user_name} ({user_email})")
          except:
            print(f"Usuario eliminado {i+1}: [No se pudo obtener información completa]")
        
        # Verificar que efectivamente existen usuarios eliminados
        assert len(user_rows) > 0, "Debería haber al menos un usuario eliminado en la lista"
        
      else:
        # Si no hay filas, verificar si hay mensaje de "No se encontraron usuarios"
        try:
          no_users_message = self.driver.find_element(By.XPATH, "//h3[contains(text(), 'No se encontraron usuarios')]")
          print("⚠️  No se encontraron usuarios eliminados en el sistema")
          pytest.skip("No hay usuarios eliminados para mostrar en el filtro")
        except:
          pytest.fail("No se pudo determinar el estado de la lista de usuarios eliminados")
          
    except Exception as e:
      pytest.fail(f"Error al verificar la lista de usuarios eliminados: {str(e)}")
    
    print("✅ Test completado: Filtro de usuarios eliminados funciona correctamente")
  