# Generated by Selenium IDE - Refactored + FIX Radix Modal
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestApelacion:

    def setup_method(self):
        self.driver = webdriver.Firefox()
        self.wait = WebDriverWait(self.driver, 12)
        self.driver.set_window_size(1280, 900)

    def teardown_method(self):
        self.driver.quit()

    # ------------------------------
    # LOGIN
    # ------------------------------
    def login(self):
        self.driver.get("http://localhost:5173/login")

        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("alexflakito15@gmail.com")

        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("14052003@leX")

        self.driver.find_element(By.CSS_SELECTOR, ".whitespace-nowrap").click()

        # Esperar dashboard
        try:
            self.wait.until(EC.url_contains("/dashboard"))
        except:
            self.driver.get("http://localhost:5173/dashboard")
            self.wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
        time.sleep(1)

    # ------------------------------
    # TEST PRINCIPAL
    # ------------------------------
    def test_apelacion(self):
        self.login()

        self.driver.get("http://localhost:5173/my-incidents")
        self.wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))
        time.sleep(0.8)

        # ⭐ SOLO los botones dentro de la tabla (no el avatar)
        botones = self.driver.find_elements(
            By.CSS_SELECTOR,
            "table button[data-slot='dropdown-menu-trigger']"
        )

        assert len(botones) > 0, "❌ No se encontraron botones de menú dentro de la tabla"

        # Usamos el primer botón visible dentro de la tabla
        menu_btn = None
        for b in botones:
            if b.is_displayed():
                menu_btn = b
                break

        assert menu_btn is not None, "❌ No hay botón visible en la tabla"

        # Abrir menú Radix con ActionChains
        from selenium.webdriver import ActionChains
        ActionChains(self.driver).move_to_element(menu_btn).click().perform()

        # Esperar aparición del menú
        opcion_menu = self.wait.until(
            EC.visibility_of_element_located((By.CSS_SELECTOR, "[role='menuitem']"))
        )
        opcion_menu.click()

        # Esperar modal Radix
        motivo_input = self.wait.until(
            EC.visibility_of_element_located((By.ID, "reason"))
        )
        motivo_input.send_keys("esta esta mal")

        enviar_btn = self.wait.until(
            EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Enviar')]"))
        )
        enviar_btn.click()

        time.sleep(1)
        print("✅ Test completado")
