import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException


class TestBorrarCuenta:
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.wait = WebDriverWait(self.driver, 15)
    self.driver.set_window_size(1280, 900)

  def teardown_method(self, method):
    self.driver.quit()

  def login(self, email: str, password: str):
    driver = self.driver
    wait = self.wait
    driver.get("http://localhost:5173/login")
    wait.until(EC.visibility_of_element_located((By.ID, "email"))).clear()
    wait.until(EC.visibility_of_element_located((By.ID, "email"))).send_keys(email)
    wait.until(EC.visibility_of_element_located((By.ID, "password"))).clear()
    wait.until(EC.visibility_of_element_located((By.ID, "password"))).send_keys(password)
    wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']"))).click()
    wait.until(EC.url_contains("/dashboard"))

  def test_borrar_cuenta(self):
    driver = self.driver
    wait = self.wait

    # 1) Login con la cuenta que se eliminará
    self.login("test@gmail.com", "test1234")

    # 2) Abrir menú de usuario
    profile_btn = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[data-slot='dropdown-menu-trigger']")))
    driver.execute_script("arguments[0].scrollIntoView({block:'center'});", profile_btn)
    profile_btn.click()

    # 3) Click en "Eliminar cuenta" dentro del menú (Radix)
    wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, "[role='menu']")))
    eliminar_item = wait.until(EC.element_to_be_clickable((
      By.XPATH,
      "//div[@role='menuitem' or @role='menuitemradio' or @role='menuitemcheckbox'][contains(., 'Eliminar cuenta') or contains(., 'Eliminar')]"
    )))
    driver.execute_script("arguments[0].click();", eliminar_item)

    # 4) Modal de confirmación: título 'Eliminar cuenta' y botón 'Eliminar cuenta'
    dialog = wait.until(EC.visibility_of_element_located((
      By.XPATH,
      "//div[@role='dialog' and .//h2[contains(normalize-space(),'Eliminar cuenta')]]"
    )))
    confirmar_btn = wait.until(EC.element_to_be_clickable((
      By.XPATH,
      "//div[@role='dialog']//button[contains(normalize-space(),'Eliminar cuenta')]"
    )))
    driver.execute_script("arguments[0].scrollIntoView({block:'center'});", confirmar_btn)
    driver.execute_script("arguments[0].click();", confirmar_btn)

    # 5) Redirección a login
    wait.until(EC.url_contains("/login"))

    # 6) Intentar iniciar sesión nuevamente con la cuenta eliminada
    wait.until(EC.visibility_of_element_located((By.ID, "email"))).clear()
    driver.find_element(By.ID, "email").send_keys("test@gmail.com")
    wait.until(EC.visibility_of_element_located((By.ID, "password"))).clear()
    driver.find_element(By.ID, "password").send_keys("test1234")
    wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[type='submit']"))).click()

    # 7) Validación: no debe permitir acceso al dashboard y debe mostrar error/toast
    # Si llega al dashboard, es un error.
    try:
      WebDriverWait(driver, 6).until(EC.url_contains("/dashboard"))
      assert False, "El usuario eliminado no debería poder iniciar sesión"
    except TimeoutException:
      pass

    # Opcional: esperar algún mensaje de error o toast
    try:
      WebDriverWait(driver, 8).until(EC.presence_of_element_located((
        By.XPATH,
        "//*[@role='alert' or contains(@class,'sonner') or contains(normalize-space(),'eliminad') or contains(normalize-space(),'inválid') or contains(normalize-space(),'invalid') or contains(normalize-space(),'desactiv') or contains(normalize-space(),'bloquead') or contains(normalize-space(),'suspend')]"
      )))
    except TimeoutException:
      # Como mínimo, confirmar que seguimos en /login
      assert "/login" in driver.current_url
# Generated by Selenium IDE
